export const seedCvProfiles = [
  {
    id: "cv-seed-001",
    title: "Full-Stack Developer CV",
    focus: "fullstack",
    personalInfo: JSON.stringify({
      name: "Alex Morgan",
      email: "alex.morgan@devstudio.io",
      phone: "+1 415 555 0192",
      location: "San Francisco, CA",
      linkedin: "linkedin.com/in/alexmorgan",
      github: "github.com/alexmorgan",
      website: "alexmorgan.dev",
    }),
    summary:
      "Full-stack engineer with 6+ years building scalable web applications. Specialises in TypeScript, React, Node.js and PostgreSQL. Passionate about clean architecture and developer experience.",
    experience: JSON.stringify([
      {
        title: "Senior Full-Stack Engineer",
        company: "Vercel",
        location: "Remote",
        startDate: "2022-03",
        endDate: "",
        current: true,
        bullets: [
          "Led migration of monolith to microservices, reducing deploy time by 60%",
          "Architected real-time collaboration features serving 50k+ concurrent users",
          "Mentored 4 junior engineers and drove team code-review culture",
        ],
      },
      {
        title: "Frontend Engineer",
        company: "Shopify",
        location: "Toronto, Canada",
        startDate: "2020-06",
        endDate: "2022-02",
        current: false,
        bullets: [
          "Built and maintained Polaris design system components used by 1M+ merchants",
          "Improved Lighthouse performance scores from 62 to 94 across 12 pages",
          "Collaborated with UX team to ship checkout redesign with 8% conversion lift",
        ],
      },
      {
        title: "Junior Developer",
        company: "Startup Studio",
        location: "New York, NY",
        startDate: "2018-09",
        endDate: "2020-05",
        current: false,
        bullets: [
          "Developed 3 MVP products end-to-end using React and Express",
          "Integrated Stripe payments and reduced churn with subscription analytics",
        ],
      },
    ]),
    skills: JSON.stringify({
      frontend: ["React", "TypeScript", "Next.js", "Tailwind CSS", "Vite", "GraphQL"],
      backend: ["Node.js", "Express", "PostgreSQL", "Redis", "Drizzle ORM", "REST APIs"],
      devops: ["Docker", "GitHub Actions", "Vercel", "AWS EC2", "Nginx", "Linux"],
      tools: ["Git", "Figma", "Postman", "Sentry", "Datadog"],
    }),
    education: JSON.stringify([
      {
        degree: "B.Sc. Computer Science",
        institution: "UC Berkeley",
        location: "Berkeley, CA",
        startDate: "2014-09",
        endDate: "2018-05",
        gpa: "3.8",
      },
    ]),
    projects: JSON.stringify([
      {
        name: "OpenBoard",
        description: "Real-time collaborative whiteboard built with React and WebSockets. 2k+ GitHub stars.",
        url: "github.com/alexmorgan/openboard",
        tags: ["React", "Node.js", "Socket.io"],
      },
      {
        name: "QueryCraft",
        description: "AI-powered SQL query builder that generates optimised queries from plain English.",
        url: "querycraft.dev",
        tags: ["TypeScript", "OpenAI", "PostgreSQL"],
      },
    ]),
    languages: JSON.stringify([
      { language: "English", level: "native" },
      { language: "Spanish", level: "intermediate" },
    ]),
    category: "fullstack",
    tags: ["react", "typescript", "node", "postgres"],
    slug: "fullstack-developer-cv",
  },
  {
    id: "cv-seed-002",
    title: "Backend Engineer CV",
    focus: "backend",
    personalInfo: JSON.stringify({
      name: "Sam Rivera",
      email: "sam.rivera@devstudio.io",
      phone: "+44 7911 123456",
      location: "London, UK",
      linkedin: "linkedin.com/in/samrivera",
      github: "github.com/samrivera",
      website: "",
    }),
    summary:
      "Backend engineer with 5 years' experience designing high-throughput APIs and distributed systems. Strong background in Python, Go and cloud-native architecture on AWS.",
    experience: JSON.stringify([
      {
        title: "Backend Engineer",
        company: "Monzo",
        location: "London, UK",
        startDate: "2021-01",
        endDate: "",
        current: true,
        bullets: [
          "Designed event-driven microservices processing 2M+ transactions per day",
          "Reduced p99 API latency from 340 ms to 48 ms via query optimisation and caching",
          "Owned on-call rotation and led post-mortems for 3 major incidents",
        ],
      },
      {
        title: "Software Engineer",
        company: "Thoughtworks",
        location: "Manchester, UK",
        startDate: "2019-03",
        endDate: "2020-12",
        current: false,
        bullets: [
          "Delivered backend services for 6 client projects across fintech and retail sectors",
          "Introduced contract testing with Pact, reducing integration bugs by 40%",
        ],
      },
    ]),
    skills: JSON.stringify({
      languages: ["Python", "Go", "TypeScript", "SQL"],
      frameworks: ["FastAPI", "Django", "Gin", "Express"],
      databases: ["PostgreSQL", "Redis", "MongoDB", "Cassandra"],
      cloud: ["AWS Lambda", "ECS", "RDS", "SQS", "Terraform", "Kubernetes"],
    }),
    education: JSON.stringify([
      {
        degree: "M.Eng. Software Engineering",
        institution: "University of Manchester",
        location: "Manchester, UK",
        startDate: "2017-09",
        endDate: "2019-02",
        gpa: "",
      },
    ]),
    projects: JSON.stringify([
      {
        name: "RateLimitX",
        description: "Open-source distributed rate limiter using Redis sliding window algorithm.",
        url: "github.com/samrivera/ratelimitx",
        tags: ["Go", "Redis", "Docker"],
      },
    ]),
    languages: JSON.stringify([
      { language: "English", level: "fluent" },
      { language: "Portuguese", level: "native" },
    ]),
    category: "backend",
    tags: ["python", "go", "aws", "microservices"],
    slug: "backend-engineer-cv",
  },
  {
    id: "cv-seed-003",
    title: "Frontend Developer CV",
    focus: "frontend",
    personalInfo: JSON.stringify({
      name: "Jamie Lee",
      email: "jamie.lee@devstudio.io",
      phone: "+1 628 555 0147",
      location: "Austin, TX",
      linkedin: "linkedin.com/in/jamielee",
      github: "github.com/jamielee",
      website: "jamielee.design",
    }),
    summary:
      "Creative frontend developer with 4 years building pixel-perfect, accessible UIs. Expert in React, animation libraries, and design systems. Bridges the gap between design and engineering.",
    experience: JSON.stringify([
      {
        title: "Frontend Engineer",
        company: "Linear",
        location: "Remote",
        startDate: "2022-05",
        endDate: "",
        current: true,
        bullets: [
          "Built and shipped 20+ UI features in React with sub-16 ms render times",
          "Owned the design-token system used across web and mobile apps",
          "Led accessibility audit resulting in WCAG 2.1 AA compliance",
        ],
      },
      {
        title: "UI Developer",
        company: "Agency Creative",
        location: "Austin, TX",
        startDate: "2020-01",
        endDate: "2022-04",
        current: false,
        bullets: [
          "Delivered 15+ marketing sites for Fortune 500 clients",
          "Reduced average build time by 35% by migrating to Vite",
        ],
      },
    ]),
    skills: JSON.stringify({
      core: ["React", "TypeScript", "Next.js", "CSS", "HTML5"],
      styling: ["Tailwind CSS", "CSS Modules", "Framer Motion", "GSAP"],
      testing: ["Vitest", "Playwright", "Storybook"],
      design: ["Figma", "Adobe XD", "WCAG 2.1", "Design Systems"],
    }),
    education: JSON.stringify([
      {
        degree: "B.A. Interactive Media Design",
        institution: "UT Austin",
        location: "Austin, TX",
        startDate: "2016-09",
        endDate: "2020-05",
        gpa: "3.7",
      },
    ]),
    projects: JSON.stringify([
      {
        name: "MotionKit",
        description: "React animation component library with 30+ ready-to-use animated primitives.",
        url: "motionkit.dev",
        tags: ["React", "Framer Motion", "Storybook"],
      },
    ]),
    languages: JSON.stringify([
      { language: "English", level: "native" },
      { language: "Korean", level: "basic" },
    ]),
    category: "frontend",
    tags: ["react", "animations", "design-systems", "accessibility"],
    slug: "frontend-developer-cv",
  },
  {
    id: "cv-seed-004",
    title: "DevOps Engineer CV",
    focus: "general",
    personalInfo: JSON.stringify({
      name: "Jordan Kim",
      email: "jordan.kim@devstudio.io",
      phone: "+1 206 555 0183",
      location: "Seattle, WA",
      linkedin: "linkedin.com/in/jordankim",
      github: "github.com/jordankim",
      website: "",
    }),
    summary:
      "DevOps engineer with 7 years automating infrastructure and shipping software reliably. Deep expertise in Kubernetes, Terraform, and cloud-native pipelines on AWS and GCP.",
    experience: JSON.stringify([
      {
        title: "Staff DevOps Engineer",
        company: "Amazon Web Services",
        location: "Seattle, WA",
        startDate: "2020-08",
        endDate: "",
        current: true,
        bullets: [
          "Managed Kubernetes clusters handling 10k+ pods across 3 availability zones",
          "Automated IaC for 200+ microservices using Terraform and Helm",
          "Reduced mean time to recovery (MTTR) from 45 min to 8 min",
        ],
      },
      {
        title: "Cloud Infrastructure Engineer",
        company: "T-Mobile",
        location: "Bellevue, WA",
        startDate: "2017-04",
        endDate: "2020-07",
        current: false,
        bullets: [
          "Migrated 80 on-premise services to AWS, saving $1.2M annually",
          "Built CI/CD pipelines for 40 teams using Jenkins and GitHub Actions",
        ],
      },
    ]),
    skills: JSON.stringify({
      orchestration: ["Kubernetes", "Helm", "Docker", "ECS"],
      iac: ["Terraform", "Pulumi", "Ansible", "CloudFormation"],
      cloud: ["AWS", "GCP", "Azure"],
      monitoring: ["Datadog", "Prometheus", "Grafana", "PagerDuty"],
      cicd: ["GitHub Actions", "Jenkins", "ArgoCD", "CircleCI"],
    }),
    education: JSON.stringify([
      {
        degree: "B.Sc. Information Systems",
        institution: "University of Washington",
        location: "Seattle, WA",
        startDate: "2013-09",
        endDate: "2017-06",
        gpa: "",
      },
    ]),
    projects: JSON.stringify([
      {
        name: "K8s Cost Watcher",
        description: "Kubernetes operator that monitors pod resource usage and alerts on cost anomalies.",
        url: "github.com/jordankim/k8s-cost-watcher",
        tags: ["Go", "Kubernetes", "Prometheus"],
      },
    ]),
    languages: JSON.stringify([
      { language: "English", level: "native" },
      { language: "Japanese", level: "intermediate" },
    ]),
    category: "devops",
    tags: ["kubernetes", "terraform", "aws", "cicd"],
    slug: "devops-engineer-cv",
  },
];
