export const seedFreelanceOffers = [
  {
    id: "offer-seed-001",
    title: "E-commerce Platform with React & Stripe",
    client: "RetailBoost Agency",
    platform: "Upwork",
    budget: "$3,500",
    currency: "USD",
    status: "accepted",
    description:
      "Build a full-stack e-commerce store with product catalogue, cart, Stripe checkout, order management, and admin dashboard. Tech: React 19, Node.js, PostgreSQL.",
    url: "https://upwork.com/jobs/ecommerce-react-stripe",
    deadline: "2025-08-15",
    category: "fullstack",
    tags: ["react", "stripe", "ecommerce", "node"],
    notes: "Client wants weekly demos. Milestone 1 payment received.",
  },
  {
    id: "offer-seed-002",
    title: "SaaS Dashboard Redesign",
    client: "AnalyticsHub",
    platform: "Fiverr",
    budget: "$1,200",
    currency: "USD",
    status: "in_review",
    description:
      "Redesign an existing analytics dashboard with modern UI, dark mode, responsive layout, and interactive recharts-based charts. Figma designs provided.",
    url: "https://fiverr.com/offers/saas-dashboard",
    deadline: "2025-07-30",
    category: "frontend",
    tags: ["react", "tailwind", "recharts", "figma"],
    notes: "Awaiting client review of the first mockup revision.",
  },
  {
    id: "offer-seed-003",
    title: "REST API Development — Healthcare App",
    client: "MediTrack",
    platform: "Mostaql",
    budget: "$2,800",
    currency: "USD",
    status: "new",
    description:
      "Design and build a HIPAA-compliant REST API for a patient management system. Includes auth, appointments, records, and billing endpoints using Node.js + PostgreSQL.",
    url: "https://mostaql.com/projects/healthcare-api",
    deadline: "2025-09-01",
    category: "backend",
    tags: ["node", "express", "postgresql", "hipaa"],
    notes: "Need to review HIPAA compliance requirements before quoting.",
  },
  {
    id: "offer-seed-004",
    title: "WordPress to Next.js Migration",
    client: "BlogSphere Media",
    platform: "Freelancer",
    budget: "$950",
    currency: "USD",
    status: "completed",
    description:
      "Migrate a WordPress blog (200+ posts) to a headless Next.js app with sanity.io CMS, preserving all URLs for SEO and improving Core Web Vitals.",
    url: "https://freelancer.com/projects/nextjs-migration",
    deadline: "2025-06-10",
    category: "frontend",
    tags: ["next.js", "sanity", "seo", "migration"],
    notes: "Delivered on time. Client left 5-star review. Great reference project.",
  },
  {
    id: "offer-seed-005",
    title: "Real-Time Chat Feature Integration",
    client: "TeamCollab Inc.",
    platform: "Upwork",
    budget: "$1,800",
    currency: "USD",
    status: "in_review",
    description:
      "Add real-time chat to an existing React app using WebSockets (Socket.io), with message history, typing indicators, online presence, and file sharing.",
    url: "https://upwork.com/jobs/realtime-chat",
    deadline: "2025-08-05",
    category: "fullstack",
    tags: ["socket.io", "react", "redis", "node"],
    notes: "Demo delivered. Waiting for QA sign-off from their team.",
  },
  {
    id: "offer-seed-006",
    title: "Mobile App UI with React Native",
    client: "FitTrack Startup",
    platform: "Khamsat",
    budget: "$2,100",
    currency: "USD",
    status: "new",
    description:
      "Build the UI layer for a fitness tracking app in React Native (Expo). Includes home dashboard, workout logs, nutrition tracker, and progress charts.",
    url: "https://khamsat.com/projects/fitness-app-ui",
    deadline: "2025-09-20",
    category: "mobile",
    tags: ["react-native", "expo", "charts", "fitness"],
    notes: "Client has detailed Figma designs ready. Timeline seems tight — need to clarify scope.",
  },
  {
    id: "offer-seed-007",
    title: "CI/CD Pipeline Setup & Docker Deployment",
    client: "LogixSoft",
    platform: "PeoplePerHour",
    budget: "$750",
    currency: "USD",
    status: "accepted",
    description:
      "Set up GitHub Actions CI/CD pipeline with automated testing, Docker multi-stage builds, and deployment to AWS EC2 with Nginx reverse proxy.",
    url: "https://peopleperhour.com/projects/cicd-docker",
    deadline: "2025-07-20",
    category: "devops",
    tags: ["docker", "github-actions", "aws", "nginx"],
    notes: "Started onboarding. Received access to their GitHub org and AWS account.",
  },
  {
    id: "offer-seed-008",
    title: "AI Chatbot Integration — Customer Support",
    client: "RetailPro",
    platform: "Upwork",
    budget: "$4,200",
    currency: "USD",
    status: "new",
    description:
      "Integrate an OpenAI-powered chatbot into an existing support portal. Includes RAG with product docs, conversation history, escalation to human agents, and analytics.",
    url: "https://upwork.com/jobs/ai-chatbot-support",
    deadline: "2025-10-01",
    category: "ai",
    tags: ["openai", "rag", "langchain", "react"],
    notes: "Large budget — this is a priority lead. Schedule a discovery call this week.",
  },
];
