export const seedJobs = [
  {
    id: "job-seed-001",
    title: "Senior Full-Stack Engineer",
    company: "Stripe",
    location: "San Francisco, CA",
    url: "https://stripe.com/jobs/listing/senior-fullstack-engineer",
    platform: "LinkedIn",
    status: "interview",
    salary: "$180,000 – $230,000",
    remote: true,
    category: "fullstack",
    tags: ["react", "typescript", "go", "distributed-systems"],
    notes: "Interviewed with the payments team. Technical round scheduled for next week.",
  },
  {
    id: "job-seed-002",
    title: "Frontend Engineer",
    company: "Vercel",
    location: "Remote",
    url: "https://vercel.com/careers/frontend-engineer",
    platform: "LinkedIn",
    status: "applied",
    salary: "$150,000 – $190,000",
    remote: true,
    category: "frontend",
    tags: ["react", "next.js", "typescript", "performance"],
    notes: "Applied via referral from a former colleague. Awaiting recruiter screen.",
  },
  {
    id: "job-seed-003",
    title: "Backend Engineer — Payments",
    company: "Shopify",
    location: "Toronto, Canada",
    url: "https://shopify.com/careers/backend-engineer-payments",
    platform: "Indeed",
    status: "applied",
    salary: "$140,000 – $180,000 CAD",
    remote: true,
    category: "backend",
    tags: ["ruby", "go", "kafka", "postgresql"],
    notes: "Strong culture fit. Need to brush up on Ruby on Rails before the take-home.",
  },
  {
    id: "job-seed-004",
    title: "Staff Software Engineer",
    company: "Linear",
    location: "Remote",
    url: "https://linear.app/careers/staff-engineer",
    platform: "AngelList",
    status: "saved",
    salary: "$200,000 – $260,000",
    remote: true,
    category: "fullstack",
    tags: ["react", "typescript", "node", "real-time"],
    notes: "Dream job. Need to build a stronger portfolio project first.",
  },
  {
    id: "job-seed-005",
    title: "DevOps Engineer",
    company: "HashiCorp",
    location: "Remote",
    url: "https://hashicorp.com/jobs/devops-engineer",
    platform: "We Work Remotely",
    status: "saved",
    salary: "$160,000 – $200,000",
    remote: true,
    category: "devops",
    tags: ["terraform", "kubernetes", "vault", "aws"],
    notes: "Great alignment with my Terraform experience.",
  },
  {
    id: "job-seed-006",
    title: "React Native Engineer",
    company: "Coinbase",
    location: "Remote",
    url: "https://coinbase.com/careers/react-native",
    platform: "LinkedIn",
    status: "rejected",
    salary: "$170,000 – $210,000",
    remote: true,
    category: "mobile",
    tags: ["react-native", "typescript", "web3"],
    notes: "Didn't progress after the system design round. Asked for feedback.",
  },
  {
    id: "job-seed-007",
    title: "Platform Engineer",
    company: "GitHub",
    location: "Remote",
    url: "https://github.com/about/careers/platform-engineer",
    platform: "Glassdoor",
    status: "offer",
    salary: "$185,000 – $235,000",
    remote: true,
    category: "backend",
    tags: ["ruby", "go", "mysql", "kubernetes"],
    notes: "Received offer! Negotiating equity and signing bonus. Decision by Friday.",
  },
  {
    id: "job-seed-008",
    title: "Senior Frontend Engineer",
    company: "Figma",
    location: "San Francisco, CA",
    url: "https://figma.com/careers/senior-frontend",
    platform: "LinkedIn",
    status: "saved",
    salary: "$175,000 – $220,000",
    remote: false,
    category: "frontend",
    tags: ["typescript", "canvas", "webgl", "react"],
    notes: "Very interesting WebGL challenge. Need to learn more about canvas APIs first.",
  },
  {
    id: "job-seed-009",
    title: "Backend Engineer — Infrastructure",
    company: "Cloudflare",
    location: "Remote",
    url: "https://cloudflare.com/careers/backend-infra",
    platform: "RemoteOK",
    status: "applied",
    salary: "$155,000 – $195,000",
    remote: true,
    category: "backend",
    tags: ["rust", "go", "networking", "edge"],
    notes: "Edge computing role. Learning Rust on the side to strengthen this application.",
  },
  {
    id: "job-seed-010",
    title: "Full-Stack Engineer",
    company: "Notion",
    location: "San Francisco, CA",
    url: "https://notion.so/careers/fullstack",
    platform: "LinkedIn",
    status: "interview",
    salary: "$160,000 – $200,000",
    remote: false,
    category: "fullstack",
    tags: ["react", "typescript", "node", "postgresql"],
    notes: "Passed initial screen. On-site loop scheduled with 4 engineers.",
  },
];
