export const seedMyServices = [
  {
    id: "service-seed-001",
    title: "Full-Stack Web App Development",
    platform: "Upwork",
    url: "https://upwork.com/freelancers/alexmorgan-fullstack",
    category: "fullstack",
    price: "$65",
    currency: "USD",
    status: "active",
    description:
      "End-to-end web application development using React, TypeScript, Node.js, and PostgreSQL. Includes clean architecture, API design, auth, deployment, and documentation. Perfect for SaaS MVPs and internal tools.",
    deliveryDays: 14,
    tags: ["react", "node", "typescript", "postgresql", "saas"],
    notes: "Top-rated on Upwork. 98% job success score. Average project size $2,500.",
  },
  {
    id: "service-seed-002",
    title: "React UI Component Library",
    platform: "Fiverr",
    url: "https://fiverr.com/alexmorgan/react-components",
    category: "frontend",
    price: "$199",
    currency: "USD",
    status: "active",
    description:
      "Custom React component library built to match your Figma design system. Includes Button, Input, Modal, Table, Dropdown, Tabs, and 15+ more components — fully typed, tested with Vitest, and documented in Storybook.",
    deliveryDays: 7,
    tags: ["react", "storybook", "figma", "typescript", "design-system"],
    notes: "Best seller gig. Upsell with Tailwind theming add-on (+$99).",
  },
  {
    id: "service-seed-003",
    title: "REST API Design & Development",
    platform: "Mostaql",
    url: "https://mostaql.com/u/alexmorgan/services/rest-api",
    category: "backend",
    price: "$45",
    currency: "USD",
    status: "active",
    description:
      "Production-ready REST API built with Node.js + Express (or FastAPI for Python). Includes OpenAPI docs, JWT auth, rate limiting, input validation, error handling, and PostgreSQL integration.",
    deliveryDays: 5,
    tags: ["node", "express", "rest", "postgresql", "jwt"],
    notes: "Offer hourly rate for large projects. Minimum 10 endpoints.",
  },
  {
    id: "service-seed-004",
    title: "CI/CD Pipeline & Docker Setup",
    platform: "PeoplePerHour",
    url: "https://peopleperhour.com/freelancer/alexmorgan/devops",
    category: "devops",
    price: "$299",
    currency: "USD",
    status: "active",
    description:
      "Complete CI/CD setup with GitHub Actions, Docker multi-stage builds, automated tests, and deployment to your cloud of choice (AWS, GCP, DigitalOcean). Includes Nginx config, SSL, and monitoring setup.",
    deliveryDays: 3,
    tags: ["docker", "github-actions", "aws", "nginx", "ssl"],
    notes: "Add-on: Kubernetes deployment available (+$150). Very quick turnaround.",
  },
  {
    id: "service-seed-005",
    title: "Website Performance Audit & Optimisation",
    platform: "Fiverr",
    url: "https://fiverr.com/alexmorgan/performance-audit",
    category: "frontend",
    price: "$149",
    currency: "USD",
    status: "active",
    description:
      "Full Lighthouse audit with actionable fixes for Core Web Vitals (LCP, CLS, FID). Includes image optimisation, code splitting, lazy loading, bundle analysis, and a detailed report with before/after scores.",
    deliveryDays: 2,
    tags: ["performance", "lighthouse", "core-web-vitals", "react", "seo"],
    notes: "Fast turnaround gig. High conversion rate. Consider raising price to $199.",
  },
  {
    id: "service-seed-006",
    title: "AI Feature Integration (OpenAI / Claude)",
    platform: "Upwork",
    url: "https://upwork.com/freelancers/alexmorgan-ai",
    category: "ai",
    price: "$85",
    currency: "USD",
    status: "active",
    description:
      "Add AI-powered features to your existing app — chatbots, summarisation, document Q&A (RAG), code generation assistants, image analysis, or structured data extraction. Works with OpenAI, Anthropic Claude, and Google Gemini.",
    deliveryDays: 7,
    tags: ["openai", "claude", "rag", "langchain", "ai"],
    notes: "Growing demand. Consider creating a separate Fiverr gig specifically for RAG chatbots.",
  },
  {
    id: "service-seed-007",
    title: "Database Design & Optimisation",
    platform: "Khamsat",
    url: "https://khamsat.com/user/alexmorgan/db-optimisation",
    category: "backend",
    price: "$120",
    currency: "USD",
    status: "paused",
    description:
      "PostgreSQL schema design from scratch or optimisation of existing databases. Includes normalisation, indexing strategy, query optimisation with EXPLAIN ANALYZE, and migration scripts.",
    deliveryDays: 4,
    tags: ["postgresql", "indexing", "schema", "query-optimisation"],
    notes: "Paused to focus on higher-value gigs. Re-activate in Q3 if demand picks up.",
  },
  {
    id: "service-seed-008",
    title: "Landing Page & Marketing Site",
    platform: "Freelancer",
    url: "https://freelancer.com/u/alexmorgan/landing-pages",
    category: "frontend",
    price: "$399",
    currency: "USD",
    status: "draft",
    description:
      "High-converting landing page built with Next.js and Tailwind CSS. Includes hero, features, pricing, testimonials, FAQ, and contact sections. SEO-optimised, fully responsive, and integrated with your CRM or email tool.",
    deliveryDays: 5,
    tags: ["next.js", "tailwind", "landing-page", "seo", "conversion"],
    notes: "Draft — finalise pricing and add portfolio examples before publishing.",
  },
];
