import type { InterviewQuestionSeed } from "./types.js";

const now = Date.now();

export const backendGeneralQuestions: InterviewQuestionSeed[] = [
  {
    id: "iq_be_1",
    area: "backend",
    difficulty: "junior",
    category: "Databases",
    question: "What is the difference between SQL and NoSQL databases?",
    answer: "SQL: relational, structured table format, predefined schema, supports complex JOINs and transaction safety (ACID). Best for transactional, structured systems (e.g., banking). NoSQL: non-relational, flexible schema (documents, key-value, graph), optimized for horizontal scaling and rapid iteration. Best for unstructured data, high write throughput.",
    tags: ["databases", "sql", "nosql"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_be_2",
    area: "backend",
    difficulty: "mid",
    category: "Databases",
    question: "What is database indexing and how does it improve query performance?",
    answer: "An index is a data structure (typically B-Tree) that stores pointer references to table rows, allowing queries to search in O(log N) rather than O(N) sequential scans. Indexes speed up SELECT queries with WHERE/JOIN clauses, but slow down write operations (INSERT/UPDATE/DELETE) because the index itself must be updated.",
    tags: ["databases", "indexing", "performance"],
    createdAt: now,
  },
  {
    id: "iq_be_3",
    area: "backend",
    difficulty: "mid",
    category: "API Design",
    question: "Explain the difference between REST, GraphQL, and gRPC.",
    answer: "REST: resource-oriented, standard HTTP methods (GET/POST/PUT/DELETE), JSON payload, simple but prone to over/under-fetching. GraphQL: client-specified queries, single endpoint, strongly typed schema, prevents over-fetching. gRPC: contract-first (Protocol Buffers), HTTP/2-based streaming, binary payloads, extremely fast, ideal for internal microservices.",
    tags: ["api-design", "rest", "graphql", "grpc"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_be_4",
    area: "backend",
    difficulty: "mid",
    category: "Databases",
    question: "What is connection pooling and why is it important?",
    answer: "Creating database connections is computationally expensive. Connection pooling maintains a cache of open connections that are reused across incoming requests instead of opening/closing a connection per request. This prevents connection overhead from exhausting database limits and speeds up query execution.",
    tags: ["databases", "scaling", "performance"],
    createdAt: now,
  },
  {
    id: "iq_be_5",
    area: "backend",
    difficulty: "mid",
    category: "Security",
    question: "What are SQL injections and how do you prevent them?",
    answer: "SQL injection occurs when untrusted user input is concatenated directly into SQL queries, letting attackers execute arbitrary commands. Prevention: always use parameterized queries / prepared statements (which treat inputs as data, not executable code) or use ORMs that enforce parameterization by default.",
    tags: ["security", "sql", "backend"],
    createdAt: now,
  },
  {
    id: "iq_be_6",
    area: "backend",
    difficulty: "mid",
    category: "Databases",
    question: "What is database normalization vs denormalization?",
    answer: "Normalization: organizing data to reduce redundancy and improve data integrity (split into multiple tables, link via keys). Denormalization: intentionally adding redundant data to tables to avoid expensive JOIN operations and optimize read performance. Normalization favors writes; denormalization favors reads.",
    tags: ["databases", "database-design"],
    createdAt: now,
  },
  {
    id: "iq_be_7",
    area: "backend",
    difficulty: "mid",
    category: "Caching",
    question: "How does Redis caching work and what are cache eviction policies?",
    answer: "Redis is an in-memory key-value store used for ultra-fast data retrieval. Eviction policies define how Redis behaves when it runs out of memory. Key policies: LRU (Least Recently Used), LFU (Least Frequently Used), FIFO (First In First Out), and volatile-lru (only evict keys with an explicit expiration TTL).",
    tags: ["caching", "redis", "system-design"],
    createdAt: now,
  },
  {
    id: "iq_be_8",
    area: "backend",
    difficulty: "mid",
    category: "Security",
    question: "Explain JWT vs Session-based authentication.",
    answer: "Sessions: stateful. Server creates a session in database/Redis and sends a cookie with sessionId to client. Server validates sessionId on every request. JWT: stateless. Server signs user info into a token and sends it to client. Client sends it in Authorization header. Server verifies token signature without DB lookups. Sessions are easier to revoke; JWTs require revocation/refresh flows.",
    tags: ["security", "auth", "jwt", "sessions"],
    createdAt: now,
  },
  {
    id: "iq_be_9",
    area: "backend",
    difficulty: "senior",
    category: "Security",
    question: "What is rate limiting and how do you implement it?",
    answer: "Rate limiting prevents API abuse by capping the number of requests a user/IP can make in a timeframe. Algorithms: Token Bucket, Leaky Bucket, Sliding Window Log. Implementation: middleware in application layer using Redis to track client request counts against rate limits dynamically.",
    tags: ["security", "rate-limiting", "redis"],
    createdAt: now,
  },
  {
    id: "iq_be_10",
    area: "backend",
    difficulty: "senior",
    category: "Databases",
    question: "What is a deadlock in databases and how do you prevent/resolve it?",
    answer: "A deadlock occurs when Transaction A holds a lock on Resource 1 and waits for Resource 2, while Transaction B holds a lock on Resource 2 and waits for Resource 1. Neither can proceed. Prevention: access tables in a consistent order, keep transactions short and simple, use appropriate isolation levels, and rely on db deadlock detection/timeouts.",
    tags: ["databases", "transactions", "concurrency"],
    createdAt: now,
  },
];
