import type { InterviewQuestionSeed } from "./types.js";

const now = Date.now();

export const devopsQuestions: InterviewQuestionSeed[] = [
  {
    id: "iq_dev_1",
    area: "devops",
    difficulty: "junior",
    category: "CI/CD",
    question: "What is CI/CD and why is it important?",
    answer: "CI (Continuous Integration): merging developer changes into a shared branch frequently, triggering automated builds and tests to catch bugs early. CD (Continuous Delivery/Deployment): automating the release of checked code to staging or production environments. Benefits: faster release cycle, lower risk, automated validation.",
    tags: ["ci-cd", "automation"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_dev_2",
    area: "devops",
    difficulty: "junior",
    category: "Infrastructure",
    question: "What is Infrastructure as Code (IaC) and what are its benefits?",
    answer: "IaC is managing and provisioning infrastructure through machine-readable definition files (e.g., Terraform, Ansible) rather than manual configuration. Benefits: version-controlled configurations, repeatable setups, eliminates configuration drift, automated provisioning.",
    tags: ["infrastructure", "iac", "terraform"],
    createdAt: now,
  },
  {
    id: "iq_dev_3",
    area: "devops",
    difficulty: "junior",
    category: "Containers",
    question: "Explain the difference between virtualization (VMs) and containerization (Docker).",
    answer: "VMs: virtualize hardware, contain a full guest OS, hypervisor management, slow boot times, high memory footprint. Containers: virtualize the OS kernel, share the host OS kernel, run as isolated user space processes, lightweight, instant start times, highly portable.",
    tags: ["containers", "docker", "vms"],
    createdAt: now,
  },
  {
    id: "iq_dev_4",
    area: "devops",
    difficulty: "mid",
    category: "Networking",
    question: "What is a reverse proxy and how does it differ from a forward proxy?",
    answer: "Forward Proxy: sits in front of clients, forwards requests to external web servers (hides client identity). Reverse Proxy: sits in front of backend servers, routes client requests to appropriate servers (load balancing, SSL termination, caching). Clients only talk to the reverse proxy directly.",
    tags: ["networking", "nginx", "proxy"],
    createdAt: now,
  },
  {
    id: "iq_dev_5",
    area: "devops",
    difficulty: "mid",
    category: "Deployments",
    question: "What is blue-green deployment vs canary deployment?",
    answer: "Blue-Green: maintaining two identical environments. 'Blue' is live, 'Green' is idle where new release is deployed. Router switches traffic to Green. Rollback is instant. Canary: deploying new release to a small subset of servers / fraction of users (e.g., 5%), monitoring for errors, and slowly ramping up to 100%.",
    tags: ["deployments", "ci-cd"],
    createdAt: now,
  },
  {
    id: "iq_dev_6",
    area: "devops",
    difficulty: "mid",
    category: "Architecture",
    question: "What is the CAP theorem?",
    answer: "CAP states a distributed system can guarantee at most two out of three: Consistency (every read receives most recent write), Availability (every request receives a non-error response), Partition Tolerance (system continues to operate despite network partition). In real networks, partition tolerance is mandatory, so systems choose CP or AP.",
    tags: ["distributed-systems", "architecture"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_dev_7",
    area: "devops",
    difficulty: "mid",
    category: "Networking",
    question: "What is a CDN and how does it work?",
    answer: "CDN (Content Delivery Network) is a distributed network of edge servers that cache static assets (images, CSS, JS) geographically closer to users. It reduces latency, offloads server traffic, and improves load speeds by serving files from the nearest edge node.",
    tags: ["networking", "caching", "performance"],
    createdAt: now,
  },
  {
    id: "iq_dev_8",
    area: "devops",
    difficulty: "mid",
    category: "Security",
    question: "How does HTTPS work? (Explain TLS handshake briefly).",
    answer: "HTTPS encrypts communications over HTTP using SSL/TLS. TLS Handshake: 1. Client hello (supported ciphers). 2. Server hello + Certificate (containing server public key). 3. Client validates certificate, generates pre-master secret, encrypts with server's public key. 4. Server decrypts with private key. 5. Both establish session keys for symmetric encryption.",
    tags: ["security", "networking", "https"],
    createdAt: now,
  },
  {
    id: "iq_dev_9",
    area: "devops",
    difficulty: "senior",
    category: "Containers",
    question: "What is Kubernetes (K8s) and what are its core components?",
    answer: "Kubernetes is a container orchestration platform. Core components: Pods (smallest deployable units), Nodes (machines), Deployments (manage replica sets and state), Services (expose pods via IP/load balancer), Kubelet (node agent), Control Plane (API server, scheduler, etcd database).",
    tags: ["kubernetes", "orchestration", "scaling"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_dev_10",
    area: "devops",
    difficulty: "mid",
    category: "Scaling",
    question: "Explain horizontal vs vertical scaling.",
    answer: "Vertical: adding more resource capacity (CPU, RAM) to an existing server (scale up). Simpler but limited by hardware ceilings and introduces single points of failure. Horizontal: adding more server instances to the resource pool (scale out). Requires load balancers, enables infinite scale, handles failover.",
    tags: ["scaling", "system-design"],
    createdAt: now,
  },
];
