import type { InterviewQuestionSeed } from "./types.js";

const now = Date.now();

export const frontendCoreQuestions: InterviewQuestionSeed[] = [
  {
    id: "iq_fe_1",
    area: "frontend",
    difficulty: "junior",
    category: "Core Web",
    question: "What is the DOM and Virtual DOM? Explain the difference.",
    answer: "DOM (Document Object Model): structured browser representation of HTML. Editing DOM triggers expensive reflows/repaints. Virtual DOM: lightweight JavaScript representation of DOM. Changes are made to VDOM first, compared to real DOM (reconciliation), and only differences are surgically batch-updated.",
    tags: ["frontend", "dom", "vdom"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_fe_2",
    area: "frontend",
    difficulty: "junior",
    category: "JavaScript",
    question: "Explain event delegation in JavaScript.",
    answer: "Event delegation: binding a single event listener to a parent element rather than individual child elements. Because of event bubbling (events rise up DOM tree), actions on children trigger the parent listener. Parent uses `event.target` to identify which child was clicked. Benefits: less memory, handles dynamically added elements automatically.",
    tags: ["javascript", "events"],
    createdAt: now,
  },
  {
    id: "iq_fe_3",
    area: "frontend",
    difficulty: "junior",
    category: "Core Web",
    question: "What is the difference between local storage, session storage, and cookies?",
    answer: "Local Storage: persists data with no expiration, browser-scoped, ~5MB capacity. Session Storage: persists data for tab lifetime, deleted on tab close, ~5MB capacity. Cookies: smaller ~4KB capacity, sent automatically with HTTP requests, has expiration options, security attributes (HttpOnly, Secure) for auth.",
    tags: ["frontend", "storage", "cookies"],
    createdAt: now,
  },
  {
    id: "iq_fe_4",
    area: "frontend",
    difficulty: "mid",
    category: "Core Web",
    question: "What is CORS and how does it work?",
    answer: "CORS (Cross-Origin Resource Sharing) is a security mechanism enforced by browsers. It blocks clients from loading resources from origins other than their own, unless the target server explicitly returns headers like `Access-Control-Allow-Origin: *`. Complex requests trigger an OPTIONS 'preflight' request first.",
    tags: ["security", "cors", "network"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_fe_5",
    area: "frontend",
    difficulty: "junior",
    category: "CSS",
    question: "What is CSS specificity and how is it calculated?",
    answer: "Specificity determines which CSS rules apply to an element. Calculated as a 4-digit score: Inline styles (1000), IDs (100), Classes/pseudo-classes/attributes (10), Elements/pseudo-elements (1). Universal selector (*) has 0 specificity. `!important` overrides everything regardless of score.",
    tags: ["css", "specificity"],
    createdAt: now,
  },
  {
    id: "iq_fe_6",
    area: "frontend",
    difficulty: "senior",
    category: "JavaScript",
    question: "Explain the JavaScript event loop, microtasks, and macrotasks.",
    answer: "JS is single-threaded. Synchronous code executes first on Call Stack. When stack is empty, Event Loop checks queues. Microtask queue (Promises, queueMicrotask) has priority — all microtasks are drained before checking Macrotask queue (setTimeout, setInterval, user input). This repeats continuously.",
    tags: ["javascript", "concurrency", "event-loop"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_fe_7",
    area: "frontend",
    difficulty: "mid",
    category: "JavaScript",
    question: "What are Closures in JavaScript and what is a practical use case?",
    answer: "A closure is the combination of a function bundled together with references to its surrounding state (lexical environment). It allows an inner function to access variables from an outer function even after the outer function has returned. Use cases: data privacy (private variables/methods), currying, and memoization.",
    tags: ["javascript", "closures"],
    createdAt: now,
  },
  {
    id: "iq_fe_8",
    area: "frontend",
    difficulty: "mid",
    category: "Core Web",
    question: "What is the difference between SSR (Server-Side Rendering) and SSG (Static Site Generation)?",
    answer: "SSR: pages generated dynamically on the server for *every request*. Good for dynamic data, but increases server response time. SSG: pages generated once at *build time*. Extremely fast to serve from CDN, but data is static until next build. ISR can be used to revalidate static pages on-demand.",
    tags: ["frontend", "rendering", "ssr", "ssg"],
    createdAt: now,
  },
  {
    id: "iq_fe_9",
    area: "frontend",
    difficulty: "junior",
    category: "CSS",
    question: "What is the box model in CSS?",
    answer: "The box model represents the layout of element structures: Content (text/images), Padding (clear area around content), Border (around padding), Margin (clear area outside border). `box-sizing: border-box` makes width/height include padding and borders, making layouts much more predictable.",
    tags: ["css", "box-model"],
    createdAt: now,
  },
  {
    id: "iq_fe_10",
    area: "frontend",
    difficulty: "mid",
    category: "JavaScript",
    question: "Explain debouncing vs throttling.",
    answer: "Debouncing: delays invoking a function until after N milliseconds have elapsed since the last time it was called (e.g., search autocomplete). Throttling: guarantees executing a function at most once every N milliseconds (e.g., scroll / resize event handler).",
    tags: ["javascript", "optimization"],
    createdAt: now,
  },
];
