import type { InterviewQuestionSeed } from "./types.js";

const now = Date.now();

export const reactQuestions: InterviewQuestionSeed[] = [
  {
    id: "iq_rct_1",
    area: "frontend",
    difficulty: "junior",
    category: "React",
    question: "What is the difference between state and props in React?",
    answer: "Props: read-only data passed from parent to child components — the component cannot modify them. State: mutable data owned by the component itself, managed with useState/useReducer. When state changes, the component re-renders. Rule of thumb: if data flows in from outside, it's a prop; if data is managed inside, it's state.",
    tags: ["react", "state", "props"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_rct_2",
    area: "frontend",
    difficulty: "mid",
    category: "React",
    question: "Explain how useEffect works and what the dependency array controls.",
    answer: "useEffect runs a side effect after render. Dependency array controls when it re-runs: empty [] = runs once on mount, [dep1, dep2] = runs when those values change, no array = runs after every render. The cleanup function (returned from the effect) runs before the next effect and on unmount. Always clean up subscriptions and async ops to avoid memory leaks.",
    tags: ["react", "hooks", "useEffect"],
    createdAt: now,
  },
  {
    id: "iq_rct_3",
    area: "frontend",
    difficulty: "mid",
    category: "React",
    question: "What is the Context API and when should you use it vs a state library?",
    answer: "Context API provides a way to share data across a component tree without prop drilling. Best for low-frequency updates (theme, locale, authenticated user). For high-frequency state (form inputs, filters, real-time data), use a dedicated library (Zustand, Redux) because all context consumers re-render on every value change. Splitting contexts by update frequency mitigates this.",
    tags: ["react", "context", "state-management"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_rct_4",
    area: "frontend",
    difficulty: "mid",
    category: "React",
    question: "What is React reconciliation and how does the virtual DOM work?",
    answer: "React maintains a virtual DOM (VDOM) — a lightweight JS representation of the real DOM. On state change, React creates a new VDOM tree and diffs it against the previous (reconciliation). It applies only the minimal set of real DOM mutations needed. Key prop helps React identify list items and avoid unnecessary unmounts on reorder.",
    tags: ["react", "virtual-dom", "reconciliation"],
    createdAt: now,
  },
  {
    id: "iq_rct_5",
    area: "frontend",
    difficulty: "senior",
    category: "React",
    question: "What are React Server Components and how do they change the data fetching model?",
    answer: "RSCs render exclusively on the server — their code is never sent to the browser. They can query databases and external APIs directly, reducing waterfalls. They cannot use hooks or browser APIs. Client Components ('use client') still run in the browser for interactivity. RSCs enable a component-level server/client split, replacing the page-level getServerSideProps model.",
    tags: ["react", "rsc", "server-components", "nextjs"],
    favorite: true,
    createdAt: now,
  },
  {
    id: "iq_rct_6",
    area: "frontend",
    difficulty: "senior",
    category: "React",
    question: "How do useMemo and useCallback differ, and when should you actually use them?",
    answer: "useMemo caches the result of an expensive computation. useCallback caches a function reference. Both re-compute when dependencies change. Only use them when: (1) a child wrapped in React.memo needs a stable reference to avoid re-renders, or (2) a computation is genuinely expensive (measured with profiler). Premature memoization adds complexity without benefit — React is fast by default.",
    tags: ["react", "performance", "hooks", "useMemo", "useCallback"],
    createdAt: now,
  },
];
